sudo: false

language: java

jdk:
- oraclejdk8

addons:
  apt:
    packages:
    # Update to latest java version
    - oracle-java8-installer

cache:
  directories:
  - ~/.m2

env:
  global:
  - secure: "elEBSzU7KHyY+tYconN7ISI1OaRq/C3NSviIc62KdeatVdKiRfjFsfJA0sfbDcsQCcW5nNUN8P2Gaatw/ph8WlqnZSb35YhMgQnYu7ssIm1Mpz2qs9lcffOG1RTUG1L6bOvwXxbxjFsCOBmxML9QiFaUNoQZfw6hbMQkkRQxfvPLlt9gL2e1A6y8UnqZCmB7nbJFy/RaBNhpIZqFgh0Z7JqGL2jjMr+OkBqVJlSI6u3VnMr9WYDlg69MUmaWQovHCpe2UuT1wU6YnQAMD2FJCpuTgigyW876ZUsI2T2Z9OMuZm+GANS5zA9C13piNeOvz6Rm1C4ZtNu95CPB0x4GXxmnoT+L6xMCZ5Ba24PrV5lezG5n6+ZEnUjold5pn45wgDS/+3XQPjR4kxxxCnVuD2QdX3TjeYqPe8Fo0rsp7Ad8JfirqiXwHwZOTFiQARsCA2tb0XSWElAuKkw6N3xnejsbD2bbCNTwmgW82pnIXEMADW0uPgf7qGCaAIM/X7sWB1YPmPjjv6qKHRZKbBeX6B/+qNyEjdOhsOHyoh6Ww83xpJrq4dDr2jP8WMQNEUe1j4GMj0CVtWezQr3nHluLe86AcaUjDVUJ4infHAew14djDE9BWxs610sT3wwDoKo+o5sH67jZO8SeRD7Z+g0z7aUChxkMVh9tQBdrfhw6qpc="
  - secure: "j9idy7d7Jb9lvi2YVWW66kMEl3jFq+ukf3ndI68oIU1ySpGk9dVPXD+BK7rPf0YPCZRco37DnGLBYqtxDdjVeN9F4EoKGUrYRVcocp5l4qKJFFUCSl4W8VKkq1QOP8ABhfvRIjEaUfNFI5Ps7MZ8eHqvpbFqOd4PhVb+Bbdm2bBxP/wGQcg+361pZylgcNoKc5lltGNV4XrgnBj++8YlRYApHzGaum9UN2t7Wsxl5P6U5gFKL+FCpPUyKbHjVFbJ/awoLnEr+lVDS0FOSInu1x9ENU0V/Cpa0ttkiQ+1oOwVX401CosDUcII20ckf7y4clyiXzsA7GaxfQfv8O7mD6eLJ0hMz5KNGdUY8se0hnHglMIUMqyxNNWR8qkC3Dp+vDDUt9LZk0URslhNK2yV8w4Tfw8xLxB7glYpmYyVhC1LWnyfZlWX70fNJCbwRKfbx2uAyPCxYnS0ajidVwOVYHBXwcs+R/NASibL28//b8oSJwwV2mMM7iDJjrvJmzdeazfc6pqa6IWYcxN05N7gbY5924pVtasH0NmFCUTWEd8y2ULshUSlmNWatunfLJGG2YrFoBeN/rJDfvMpVw2+/0flwCJWHCyBSv2Amz2sei9UDHKwlMe3FKuJC53I9O3xyURE5xYlJaKgd9NRqkvdeGgJZWNYW6h/lFNZeKqMGQE="
  - secure: "E4K67wFz7QllR/AGlE6Rb+VvgbEbO0GfCT1rWORI9bVAHKGh7UnMFkSE9IkCyL9geXtWeZhsdsRpP5SwoPsvOimG+UhcPfDKraCE0o/Oc+mH2oTsd+jbv9N8/ZgKUXLgtuD0/BniIBmO1jelBeZYWuv+eic64aOHzrML9QOfGwHatWGPVMTHUesyhTImMP0MNaupnpXPWuYbUzBcv2qc0JONOjrqtMUdGXjxxnyEohWAf4WsN2J/4sg/wP1tmGAMDwB0Ob6xe/V8hmfynNFF/id1buSh2Ht1vWnbh62cdrbDQ6Y2YL+7WJ/DxJAqzSsr9+UrOnTKIWTpJWVT1crhXns7fv3FOMGnpxJecYYbBn4/HeyVEzTc50P7Lp0orwLzEMgdlv/9xUwPULIXbFSPlJEWvOgkHTDN9IDPYenkF8SKzoUQCT6SFPtlL6fDq6zK4fzTyrnFnTjyRjWvDBo4EjK0YmGngjbijwz1YI+ylFg3/ymMm5xcfmhz8pK7Vicy3KN/CAJ6jFM9U+b4V3m+HO7kzh/yb0J3MSj9JfYoTGjXtIpTdvmQe+onFoNntlgT7sknblLhgAwjSb/+eUMAssGhe73RN81FK47oKp4QcNoHbbzMLYiMgfkqW9HduHK4R2YFA6z3s++n7A0znnl+Fd8PYacttne7Nm0+Gtdjt8w="

before_install:
# Set the remote URL for the git repo for later use
- git remote set-url origin git@github.com:yahoo/fili.git

# Decrypt the GitHub SSH key
- openssl aes-256-cbc -K $encrypted_3b73c80ce5a3_key -iv $encrypted_3b73c80ce5a3_iv
  -in github_key.enc -out github_key -d
- chmod 600 github_key

# Start the SSH agent and add the GitHub SSH key
- eval `ssh-agent -s`
- ssh-add github_key

install:
# Get the correct thing for Travis to build
- travis/install.bash

before_script:
- echo "PR ${TRAVIS_PULL_REQUEST} and TAG '${TRAVIS_TAG}' Branch ${TRAVIS_BRANCH}"

script:
# Do the correct build flow steps
- travis/deploy.bash

after_success:
- echo "Success"
